### ISSUE TITLE
Allegro completo

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#10]

**Comment by OtacilioN** [comment]
Deadline restantes pro prox milestone de amanhã são Allegro completo e Níveis de Debug, tu pegas esse que eu pego os niveis.

**Comment by 5putnik** [comment]
Doin' right now

**Comment by OtacilioN** [comment]
Okay!

**Comment by 5putnik** [comment]
Done! Beautiful! Wonderful!
