### ISSUE TITLE
Criar um nome pra dupla de dois

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#13]
Eu, eu mesmo e Hugo era um nome legal, tinha até uma referência a um filme. Precisamos pensar num nome legal pra dupla.

**Comment by OtacilioN** [comment]
O nome tá dahora :+1: Vou dar close no issue e deixa definido asism mesmo.

**Comment by drbeco** [comment]
Assinalar os (todos) issues da parte **básica** como milestone v0.1
