### ISSUE TITLE
Adicionar arquivo de entrada de Dados.

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#15]

**Comment by 5putnik** [comment]
Adicionados 2 arquivos de entrada. Um extremamente simples apenas para testes iniciais e um um pouco mais complexo para testes finais. Fecharei essa issue pois já possuimos arquivos de entrada, mas isso não significa que outros possam ser adicionados caso um dos dois possuam vontade do mesmo. Sugiro sempre nomear o n-ésimo arquivo de entrada como entrarda_n_titulo.txt para ter uma certa padronização.

**Comment by drbeco** [comment]
Comentado em outro issue: por favor não mude os nomes dos arquivos de entrada. Se quiser adicionar mais exemplos, tudo bem, pode deixar com o nome que preferir nos extras.
