### ISSUE TITLE
Criar fluxograma do código

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#16]
Deve-se conter um fluxograma do código para guiar os trabalhos e para ser apresentado no arquivo PDF.

**Comment by drbeco** [comment]
Não tem necessidade de ser muito "detalhado". Basta um fluxograma com idéias gerais, desde que preciso.

**Comment by 5putnik** [comment]
Esqueci de fechar aqui. Ontem tudo foi resolvido.
