### ISSUE TITLE
Discussão sobre criar um novo label: To Do

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#17]
Eu acho interessante como forma de organização definir as tarefas que são "objetivos a se fazer" como dentro de um Label o "To Do", visando facilitar achar os issues que são objetivos a serem cumpridos através dos filtros de label.

**Comment by OtacilioN** [comment]
Então o que achas? Irei modificar por hora adicionando-os no Label "To Do", caso não aches que fica legal eu troco de volta para sem labels ou podemos trocas o nome.

**Comment by 5putnik** [comment]
Acho bastante válido. Tava sentindo falta de uma label útil para esses bugs antes dos bugs. Upvote 2/2

**Comment by drbeco** [comment]
Esse pode ficar com milestone já fechado v0.1
