### ISSUE TITLE
Sobre labels

### ISSUE THREAD

**Issue by drbeco** [5putnik/discreta12eueumesmoehugo#18]
Um label que sempre acho que me ajuda é o "Urgent"

Que outros vcs pensam que podem ajudar (além do ToDo que li em outro bug)?

**Comment by OtacilioN** [comment]
Acho que pode ser interessante também um label chamado "Doing" pra as ações que já estão sendo feitas mas não estão completadas, pois separa aquelas atividades que são para fazer daquelas que já estão sendo feitas, possibilitando visualizar melhor o que está atrasado.

**Comment by OtacilioN** [comment]
Quanto ao Label Urgent eu acho que ajuda sim a administrar as prioridades.

**Comment by drbeco** [comment]
Hum... Não sei, não. Tomar cuidado para não se sobrecarregar com burocracia.

Label é algo mais "estático", não dá para ficar usando o github para modificações tão frequentes.

**Comment by OtacilioN** [comment]
Okay!

**Comment by drbeco** [comment]
Se for para dizer como no futebol "é minha!!!", então dá para indicar que se está fazendo uma determinada tarefa ao marcar ali do lado no "assignee". Isso deve ser o suficiente para indicar "Doing" por exemplo, para que dois não façam a mesma tarefa simultaneamente.

**Comment by 5putnik** [comment]
Bem, To Do e URGENT já existem, as outras já provaram ser desnecessárias. Fechando, mas, claro, caso tenham sugestões de labels, podem reabrir. Eu mesmo não vejo mais necessidade.
