### ISSUE TITLE
variável makefile para flags do linker

### ISSUE THREAD

**Issue by drbeco** [5putnik/discreta12eueumesmoehugo#19]
A flag (ou chave) para linkar a biblioteca de threads (-lpthread) vai na variável `LDLIBS` e não na `CFLAGS`.

Variáveis do GCC no makefile:
- **CFLAGS**: flags para o compilador C (gcc)
- **CPPFLAGS**: flags para o pré-processador (C-Pré-Processor)
- **LDLIBS**: flags para o _linker_

**Comment by OtacilioN** [comment]
Okay, concertando!

**Comment by OtacilioN** [comment]
Deve-se ficar entre "," (virgula), como está lá?
assim:
LDLIBS = -Wl,--defsym,BUILD_$(DEFSYM)=0, -lpthread

**Comment by drbeco** [comment]
Não tem vírgula entre flags. 

A flag -Wl é única. Procure no `man gcc` por `-Wl` ou `-Wl,option` ou ainda busque por: 

_Pass option as an option to the linker._

As flags são "tokenizadas" por espaços em branco. E por isso também não tem espaço entre as vírgulas.

**Comment by OtacilioN** [comment]
Okay! Corrigindo...

**Comment by OtacilioN** [comment]
Corrigido!
