### ISSUE TITLE
Já que o label v0.1 está completo deve-se lançar a versão 0.1? 

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#20]
Já que completamos esse label posso dar merge do develop para o master e lançar a tag 0.1?

**Comment by drbeco** [comment]
1- sim, deve.
2- não use o título do issue para colocar o conteúdo dele. Use o título para colocar um título, e o conteúdo para escrever o conteúdo. (Parece óbvio, e é)

**Comment by 5putnik** [comment]
O release da v0.1 tinha sido lançado e esqueci de fechar. Closing.

**Comment by drbeco** [comment]
Marque todos issues com o milestone correspondente
