### ISSUE TITLE
Adicionar os arquivos de entrada para teste.

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#21]
Entrada-Petri-1, 2 ,3 presentes no link: https://www.dropbox.com/sh/vugkpyq37vob2im/AADms1KEL6qlwmcmQ7KrtK70a/discreta/fontes/c/petrinet?dl=0

**Comment by 5putnik** [comment]
A entrada 2 e 3 eu adicionei porque eu sabia o que era (impar ou par e um exemplo simples). Põe, por favor, a entrada-petri-1.txt com um título para que possa ter algum entendimento do que é. Até agora nomeei como entrada_X_titulo

**Comment by drbeco** [comment]
Ah, Hugo, por favor, não altere o nome dos arquivos.

Estou fazendo um script para corrigir os trabalhos de todos grupos e preciso da padronização.

**Comment by 5putnik** [comment]
Sorry, my bad. Re-renomeando então.

**Comment by 5putnik** [comment]
Arquivos re-renomeados.
