### ISSUE TITLE
Resolver condição de corrida

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#23]
Como vimos na reunião de hoje poderá existir um bug devido a condição de corrida das Threads, uma vez que a thread check a possibilidade de habilitar a transição, e o sistema operacional congele e troque para uma outra thread, que também procure no mesmo lugar e veja possibilidade de habilitar a transição, fazendo com que uma das threads consuma tokens fantasmas.

**Comment by 5putnik** [comment]
Exemplo sério da condição de corrida:
Run #1 do código usando entrada-petri-2.txt (jogo do ímpar ou par):

```
L0(0)
L1(0)
L2(0)
L3(0)
L4(0)
L5(0)
L6(0)
L7(973)
L8(27)
```

Run #2 

```
L0(0)
L1(0)
L2(0)
L3(0)
L4(0)
L5(0)
L6(0)
L7(981)
L8(19)
```

Run #3

```
L0(0)
L1(4294966296)
L2(0)
L3(0)
L4(0)
L5(4294966296)
L6(0)
L7(1000)
L8(1000)
```

Na terceira rodada do programa, houveram duas ocasiões onde foram tirados tokens de onde não se devia, gerando um underflow. :open_mouth: 

Gotta solve it!

**Comment by OtacilioN** [comment]
Professor @drbeco havia apresentado uma solução pra condição de corrida, senão me engano envolvia uso de variável shareada, tem em algum slide essa solução?

**Comment by OtacilioN** [comment]
Resolvido com isBusy no tipo lugar!

**Comment by drbeco** [comment]
Só comentando "post mortem", ficou muito boa a solução de vocês. Parabéns, feliz natal e um ótimo 2016
