### ISSUE TITLE
Biblioteca listao.h

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#26]
Começar a biblioteca listao.h
Ela deve conter:
- Funções de lista para os tipos lugar e flecha
- Todos os typedef vão para ela

**Comment by OtacilioN** [comment]
Falta alguma coisa na biblioteca?

**Comment by 5putnik** [comment]
Acho que não. Fechemos então aqui e, caso haja a necessidade, implementamos mais algo na biblioteca.
