### ISSUE TITLE
Modificação do tipo lugar

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#28]
A partir do momento que nem todos os lugares serão expressos na lista, é necessário, além da quantidade, especificar também o índice do lugar, portanto, adicionei na struct um int pos pra especificar esse índice do lugar.

Quis deixar documentada essa mudança e também perguntar se tá tudo ok desse jeito.

**Comment by OtacilioN** [comment]
Okay, achei legal assim, então dividi a função buscarLugar em buscarLugarPos e buscarLugarQtd, para buscar os lugares por posição ou por quantidade de tokens.

Seria últil criar as função buscarLugarAnd? Que seria pra procurar os 2 juntos?

**Comment by 5putnik** [comment]
Fechando aqui porque a discussão se encontra em outro lugar
