### ISSUE TITLE
Buscar Flecha: Or e And

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#29]
Qual a diferença entre as funções buscarFlechaAnd e buscarFlechaOr?

**Comment by OtacilioN** [comment]
A buscarFlechaAnd funciona como uma and das três variáveis, ele só retorna a flecha desejada se ela contiver as 3 informações que você está buscando, de, para, tk; Já a buscarFlechaOr funciona como uma or das três variáveis, ela retorna a flecha desejada se ela contiver apenas uma das 3 que você está buscando:

Exemplos; 
1- Você procura uma Flecha que venha de 2, vá para 3, e tenha 5 tokens; Usa-se a funcao buscarFlechaAnd nesse caso, para que os 3 pré requisitos sejam atendidos;

2- Você procura uma flecha que venha de 1 ou que vá para 3 ou que contenha 100 tokens, usa-se a funçao buscarFlechaOr nesse caso, pois a primeira flecha que atenda um dos 3 pré-requisitos retorna;

3- Você deseja procurar uma Flecha que vá pra 4, nesse caso pode-se usar uma buscarFlechaOr e passar os de e tk como negativos, já que não existem nunca serão atendidos, portanto retornará apenas a flecha que vai para 4, porém isso é gambiarra para utilizar assim, criarei as funções buscarFlechaDe, buscarFlechaPara, buscarFlechaTk.

**Comment by 5putnik** [comment]
Tipo, a gente só precisa buscar os índices de ida OU de volta.

No primeiro passo da transição, queremos ver todas as flechas que apontam para a transição e verificar se os requisitos dela estão ok.

No segundo passo da transição, queremos ver todas as flechas que partem da transição e somar aquela quantidade de tokens aos respectivos lugares.

Logo, só precisariamos de buscarflechade() e buscarflechapara().
