### ISSUE TITLE
funcao anterior

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#32]
Ha necessidade da funcao que acha o no anterior na biblioteca listao?

**Comment by 5putnik** [comment]
De cabeça não me parece ter utilidade, mas, como é uma biblioteca, acho que é melhor pecar pelo excesso que pecar pela falta.

**Comment by OtacilioN** [comment]
Será adicionada numa versão posterior!

**Comment by OtacilioN** [comment]
Feita!
