### ISSUE TITLE
Sugestão de prints

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#34]
Deixar esse post aqui para sugerirmos possíveis prints que ficariam legais pra colocar no debug.

Até o momento pensei o seguinte:
- Lugar
  - L[0] = 5 tokens
  - L0 = 5 tokens
- Flecha
  - T[0]---(3)--->L[2]
  - T0---(3)--->L2

**Comment by drbeco** [comment]
Que tal esse sugestão:

```
L0(5)---(2)--->T0---(1)--->L1(3)
```

Mostrando quantos tokens tem em cada lugar e o rótulo em cima de cada arco?

**Comment by 5putnik** [comment]
Fazer L-T-L não faria muito sentido visto que esse print é uma secção do total.

ex: se L1, 2 e 3 vão para T0 e T0 vai para L4 e 5

Não daria pra imprimir dessa forma. O que seria impresso seriam as partes

```
L1(0) ---(1)---> T0
L2(7) ---(1)---> T0
L3(2) ---(1)---> T0

T0 ---(1)---> L4(2)
T0 ---(1)---> L5(9)
```

Quanto a colocar a quantidade de tokens associado ao lugar, achei sensacional.

**Comment by drbeco** [comment]
Entendi. :ok_hand:

**Comment by OtacilioN** [comment]
Okay, fica definido assim!
