### ISSUE TITLE
Commit 100 - Pre-relase

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#35]
Estamos nos aproximando do Commit 100, e o código evoluiu bastante da versão 0.3, porém não o suficiente para estar na versão 1.0.

No Commit 100 vale a pena disponibilizar um pre-release comemorativo?

**Comment by 5putnik** [comment]
Pelo jeito que o código tá andando, talvez não dê ainda pra lançar algo especial no centésimo commit. :disappointed:

**Comment by 5putnik** [comment]
Eita, e acabei de ver que eu dei o 101º commit, e não tem nada muito funcional ainda. Closing :/
