### ISSUE TITLE
Versao 1.0 - Vespera de aniversario

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#36]
Como a versão de lançamento do programa 1.0 está prevista para o dia 13/12, véspera do meu aniversário, gostaria de poder batizá-la de "versão Ota", ou de colocar nos comentários do release no final das implementações da versão um "Happy Birthday Otacilio Neto" quase que como um Easter Egg.

Prefiro a 2° opcao :smiley:

**Comment by 5putnik** [comment]
Hahahahah
Coloca como um easter egg caso o debug seja 1 :p

**Comment by OtacilioN** [comment]
Okay, então vou dar closed :+1:
