### ISSUE TITLE
Tipo petri_t

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#37]
Percebi que faltavam dados no tipo petri_t, como, por exemplo, o total de transições e lugares. Já modifiquei isso e abri a issue pra vermos se não passa mais algo pela sua cabeça que não falte no tipo.

**Comment by OtacilioN** [comment]
Acho que fica só isso mesmo, vou dar close, caso no futuro precisemos adicionar algo reopen.
