### ISSUE TITLE
Mais de uma flecha de lugares diferentes apontam para uma transicao

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#40]
Por hora existe um problema nesse caso, primeiro ele olha a primeira flecha e checka se existe disponibilidade de remover os tokens do lugar, se tiver ele remove do lugar apontado pela flecha 1, então repete o mesmo para o segundo, o problema é que se o segundo n tiver tokens suficientes ele acaba removendo do primeiro.

**Comment by OtacilioN** [comment]
Creio ja ter começado a resolver o problema, caso o código não funcione com essa resolução desse problema dar rollback para a ultima versao commitada no develop no dia 11/12

**Comment by OtacilioN** [comment]
Please checkar os commits de hoje, aparentemente resolvido

**Comment by 5putnik** [comment]
Usar a flag era a solução, que foi solucionado no trecho

```
if(d == dd && d && dd)
```

Closing.
