### ISSUE TITLE
Atualizacao e subtracao / adicao 

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#41]
Estou com um problema, não sei se a minha atualização das listas que se procura, por exemplo, quando eu acho uma flecha tenho que apontar pra um próximo para poder procurar outra flecha, este apontamento não sei se está sendo feito da forma correta, bem como na hora de pegar de volta o lugar certo para se fazer a subtracao e as adicoes ja que os cabecas foram perdidos na hora de apontar pro proximo.

**Comment by OtacilioN** [comment]
Quanto a atualizacao tive uma ideia pra resolucao agora, criar uma funcao nova de busca, que a primeira coisa que ela faz e' passa pro prox na lista cabeca, porque ele so vai perder o cabeca internamente, mas por fora o cabeca e' mantido

**Comment by 5putnik** [comment]
Bem, tá quase tudo certo. Vou fechar essa issue e mostrar qual parte não está funcionando pra sermos mais diretos ao problema.
