### ISSUE TITLE
Adição não funciona

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#42]
Eu não quis postar isso naquele post porque eu não tenho certeza se o bug é aquele, portanto, vou mostrar apenas a saída do programa pra buscarmos o erro através disso.

```
L0(4)
L1(0)
T0 ---(1)---> L1
T1 ---(1)---> L0
L0 ---(1)---> T0
L1 ---(2)---> T1
======= INICIO DA SIMULACAO =======
-------------------------------------------------------
Transicao 0 disparou
L0(3)
L1(0)
-------------------------------------------------------
-------------------------------------------------------
Transicao 0 disparou
L0(2)
L1(0)
-------------------------------------------------------
-------------------------------------------------------
Transicao 0 disparou
L0(1)
L1(0)
-------------------------------------------------------
-------------------------------------------------------
Transicao 0 disparou
L0(0)
L1(0)
-------------------------------------------------------
-------------------------------------------------------
L0(0)
L1(0)
-------------------------------------------------------
======= FIM DA SIMULACAO ==========
```

Como pode ver, a subtração está OK, mas a adição não funciona. Procuremos então se:
- O lugar destino está funcionando
- A função de soma está realmente somando

Hoje não posso mais programar, então fica como to-do pra você, Ota, se quiser.

**Comment by OtacilioN** [comment]
Okay vou checkar isso, provavelmente é a atualização da lista, irei também dar uma mudada pra gente não perder o cabeca, criarei duas novas funcoes, a buscarprox e a buscarN

**Comment by OtacilioN** [comment]
Done! 
![image](https://cloud.githubusercontent.com/assets/10578275/11816119/24589ac8-a336-11e5-8ab9-01feefcabf76.png)
