### ISSUE TITLE
buscarXXXXXProx

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#43]
Função que serve para buscar mais de um elemento igual dentro de uma mesma lista, deve ser inserido o resultado anterior como cabeca da nova busca,
- exemplo y = buscarXXXXXProx(y, alvo);

O que ela faz é antes de iniciar a busca na lista interna aponta pra o próximo, mantendo "tpp" intacta para ter o cabeca da lista completa.

O que achas?

**Comment by 5putnik** [comment]
Acho meio desnecessária, mas, se achar necessário pra desenvolver a solução, be my guest :smiley:

**Comment by OtacilioN** [comment]
Eu ahco que a prox ajuda sim, principalmente a enxugar o código da função transição e deixar mais intendível, sem precisar apontar pra o próximo na mão.
