### ISSUE TITLE
buscarXXXXXN

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#44]
Busca pelo N-simo elemento igual na lista, serve para por exemplo para procurar a terceira flecha da lista que aponta para o lugar 5. 
- Exemplo: y = buscarXXXXXN(*tpp, 5, 3);

O que achas?

**Comment by 5putnik** [comment]
Acho meio desnecessária, mas, se achar necessário pra desenvolver a solução, be my guest :smiley:

**Comment by OtacilioN** [comment]
Okay, essa realmente no nosso código não tem muito uso não, seria mais uma função generalista para uma biblioteca de listas.
