### ISSUE TITLE
Níveis de debug

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#45]
Esqueci de avisar que eu implementei mais de um nível de debug.

Isso significa que a macro DEBUG agora, pode ser:
- 0: só mostra o essencial ao usuário
- 1: mostra um nível de debug mais leve 
- 2: mostra um nível mais profundo de debug

Deixo a issue aberta caso você queira discutir sobre o que colocar ou o que modificar em relação aos níveis de debug.

**Comment by drbeco** [comment]
Coloque explicação da compilação com/sem DEBUG num comentário dentro do `makefile`

**Comment by 5putnik** [comment]
Professor, gostaria de aproveitar que o senhor está aqui pra perguntar se tem como fazer com que o usuário adicione chaves no comando make pra gerar chaves gcc

ex: make ex12.x -ATIVA_DEBUG=1 -MAXIMO_ITERACAO=500

**Comment by drbeco** [comment]
Eu te respondi isso com mais detalhes por email, não foi? (09/Dez/15)

**Comment by 5putnik** [comment]
Desculpe, professor. Era tanto e-mail do GitHub que jurava que ainda não tinha recebido a resposta! :persevere:

**Comment by OtacilioN** [comment]
Feito, 4 níveis implementados.
- Nível A: Serve para mostrar o funcionamento da rede com a passagem dos tokens
- Nível B: Serve para mostrar algumas mensagens adicionais, como quantos tokens precisam ser removidos de tal lugar
- Nível C: Mostra erros fatais, como lugares inexistentes e flechas sem destinos.
- Nível D: Todos os outros níveis juntos.
