### ISSUE TITLE
Nova variável no tipo lugar - Condição de corrida

### ISSUE THREAD

**Issue by OtacilioN** [5putnik/discreta12eueumesmoehugo#50]
Acho que um jeito de resolver a condição de corrida é ter uma variável dentro do tipo chamada isBusy, onde quando ela está em 1 nada é feito no lugar, quando ela está em 0 lugar livre, a primeira coisa que o processo faz é ocupar essa variável, em seguida se libera.

**Comment by OtacilioN** [comment]
Solução plausível? @drbeco @5putnik

**Comment by 5putnik** [comment]
Aparentemente sim, vamos implementar isso e ver no que dá.

**Comment by OtacilioN** [comment]
Pronto, ficou assim! isBusy é um variável que marca se o lugar está livre ou ocupado
- 0 = LIVRE
- 1 = OCUPADO
