### ISSUE TITLE
Transição não está funcionando como deveria

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#51]
Então, acho que a parte da condição de corrida deve estar OK, mas parece que as transições não estão ativando quando deveriam. Ainda estou estudando essa implementação do isBusy, então não tenho certeza de onde se encontra o bug, seria legal se @OtacilioN desse uma olhada.

**Comment by OtacilioN** [comment]
Okay, creio que já achei o erro aqui, provavelmente não liberei o lugar num momento que precisava.
