### ISSUE TITLE
Paralelismo completo

### ISSUE THREAD

**Issue by 5putnik** [5putnik/discreta12eueumesmoehugo#9]

**Comment by OtacilioN** [comment]
@5putnik  vi que marcasse um commit como paralelismo 100%, então pode dar close?

**Comment by 5putnik** [comment]
@OtacilioN sim sim! E você ainda colocou a cereja no bolo. Faça as honras de fechar esse issue hahah

**Comment by OtacilioN** [comment]
ahsuhas que?
